{{ if .Values.integration.dependencies.wso2mi }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.integration.wso2mi.name}}-1
  namespace : {{ .Release.Namespace }}
  labels:
    {{- include "wso2mi.labels" . | nindent 4 }}
spec:
  {{ if .Values.integration.wso2mi.cluster.enabled }}
  replicas: {{ .Values.integration.wso2mi.cluster.replicas }}
  {{ else }}
  replicas: {{ .Values.integration.wso2mi.replicas }}
  {{ end }}  
  selector:
    matchLabels:
      deployment: {{ template "wso2mi.resource.prefix" . }}
      node: {{ template "wso2mi.resource.prefix" . }}-1
  template:
    metadata:
      {{- with .Values.integration.wso2mi.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        deployment: {{ template "wso2mi.resource.prefix" . }}
        node: {{ template "wso2mi.resource.prefix" . }}-1
    spec:
      initContainers:
        {{ if .Values.integration.dependencies.postgresql }}
        - name: init-postgresql
          image: busybox:1.32
          command: ['sh', '-c', 'echo -e "Checking for the availability of PostgreSQL Server deployment"; while ! nc -z "{{ .Values.integration.postgresql.serviceName }}" 5432; do sleep 1; printf "-"; done; echo -e "  >> PostgreSQL Server has started";']
        - name: init-postgresql-connector-download
          image: busybox:1.32
          command:
            - /bin/sh
            - "-c"
            - |
              set -e
              connector_version=42.2.5
              wget https://repo1.maven.org/maven2/org/postgresql/postgresql/${connector_version}/postgresql-${connector_version}.jar -P /postgresql-connector-jar/
          volumeMounts:
            - name: postgresql-connector-jar
              mountPath: /postgresql-connector-jar
        {{ end }}
        {{ if .Values.integration.dependencies.dashboard }}
        - name: init-wso2mi-dashboard
          image: busybox:1.32
          command: ['sh', '-c', 'echo -e "Checking for the availability of wso2mi-dashboard Server deployment"; while ! nc -z "{{ .Values.integration.dashboard.serviceName }}" 9743; do sleep 1; printf "-"; done; echo -e "  >> wso2mi-dashboard Server has started";']
        {{ end }}
      containers:
        - name: {{ .Values.integration.wso2mi.name}}
          image: "{{ .Values.integration.wso2mi.image.repository }}:{{ .Values.integration.wso2mi.image.tag }}"
          imagePullPolicy: {{ .Values.integration.wso2mi.image.pullPolicy }}
          ports:
            - containerPort: 8290
              protocol: "TCP"
            - containerPort: 8253
              protocol: "TCP"
            - containerPort: 9201
              protocol: "TCP"
          env:
            {{ if .Values.integration.dependencies.monitoring.enabled }}
            - name: JAVA_OPTS
              value: -DenablePrometheusApi=true            
            - name: instance
              value: "{{ .Values.integration.wso2mi.serviceName}}.{{ .Release.Namespace }}.svc.cluster.local:9201"
            {{ end }}       
          volumeMounts:
            - name: wso2mi-config
              mountPath: /home/wso2carbon/wso2-config-volume/conf
            {{ if .Values.integration.dependencies.postgresql }}
            - name: postgresql-connector-jar
              mountPath: /home/wso2carbon/wso2-artifact-volume/lib
            {{ end }}
            - name: wso2mi-docker-entrypoint
              mountPath: /home/wso2carbon/docker-entrypoint.sh
              subPath: docker-entrypoint.sh
      volumes:
        - name: wso2mi-config
          configMap:
            name: {{ template "wso2mi.resource.prefix" . }}-conf
            defaultMode: 420
        {{ if .Values.integration.dependencies.postgresql }}
        - name: postgresql-connector-jar
          emptyDir: {}
        {{ end }}
        - name: wso2mi-docker-entrypoint
          configMap:
            name: {{ template "wso2mi.resource.prefix" . }}-conf-docker-entrypoint
            defaultMode: 263
      {{ if .Values.integration.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.integration.serviceAccount.name }}
      {{ end }}
      securityContext:
        {{- toYaml .Values.integration.wso2mi.podSecurityContext | nindent 8 }}
      hostAliases:
        - ip: 172.28.213.133
          hostnames:
            - 1czt
{{ end }}