{{ if .Values.integration.dependencies.apim }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wso2apim.fullname" . }}
  labels:
    {{- include "wso2apim.labels" . | nindent 4 }}
spec:  
  {{- if not .Values.integration.wso2apim.autoscaling.enabled }}
  replicas: {{ .Values.integration.wso2apim.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "wso2apim.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.integration.wso2apim.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "wso2apim.selectorLabels" . | nindent 8 }}
    spec:
      {{ if .Values.integration.dependencies.postgresql }}
      initContainers:
      - name: init-postgresql
        image: busybox:1.32
        command: ['sh', '-c', 'echo -e "Checking for the availability of PostgreSQL Server deployment"; while ! nc -z "{{ .Values.integration.postgresql.serviceName }}" 5432; do sleep 1; printf "-"; done; echo -e "  >> PostgreSQL Server has started";']
      - name: init-postgresql-connector-download
        image: busybox:1.32
        command:
          - /bin/sh
          - "-c"
          - |
            set -e
            connector_version=42.2.5
            wget https://repo1.maven.org/maven2/org/postgresql/postgresql/${connector_version}/postgresql-${connector_version}.jar -P /postgresql-connector-jar/
        volumeMounts:
          - name: postgresql-connector-jar
            mountPath: /postgresql-connector-jar
      {{ end }}
      
      containers:
        - name: {{ .Values.integration.wso2apim.name }}
          image: "{{ .Values.integration.wso2apim.image.repository }}:{{ .Values.integration.wso2apim.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.integration.wso2apim.image.pullPolicy }}
          ports:
            - containerPort: 11111
              protocol: TCP
            - containerPort: 5672
              protocol: TCP
            - containerPort: 8243
              protocol: TCP
            - containerPort: 8280
              protocol: TCP
            - containerPort: 9099
              protocol: TCP
            - containerPort: 9443
              protocol: TCP
            - containerPort: 9611
              protocol: TCP
            - containerPort: 9711
              protocol: TCP
            - containerPort: 9763
              protocol: TCP
            - containerPort: 9999
              protocol: TCP
          env:
            - name: JVM_MEM_OPTS
              value: "-Xms{{ .Values.integration.wso2apim.jvm.heap.memory.xms }} -Xmx{{ .Values.integration.wso2apim.jvm.heap.memory.xmx }}"
          lifecycle:
            preStop:
              exec:
                command:  ['sh', '-c', '${WSO2_SERVER_HOME}/bin/api-manager.sh stop']
          volumeMounts:
            - name: wso2am-deployment-toml
              mountPath: /home/wso2carbon/wso2-config-volume/repository/conf
            {{ if .Values.integration.dependencies.postgresql }}
            - name: postgresql-connector-jar
              mountPath: /home/wso2carbon/wso2-artifact-volume/repository/components/dropins
            {{ end }}
          resources:
            {{- toYaml .Values.integration.wso2apim.resources | nindent 12 }}
      volumes:
        - name: wso2am-deployment-toml
          configMap:
            name: {{ template "wso2apim.resource.prefix" . }}-conf
        {{ if .Values.integration.dependencies.postgresql }}
        - name: postgresql-connector-jar
          emptyDir: {}
        {{ end }}

      {{- with .Values.integration.wso2apim.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{ if .Values.integration.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.integration.serviceAccount.name }}
      {{ end }}
      securityContext:
        {{- toYaml .Values.integration.wso2apim.podSecurityContext | nindent 8 }}
      {{- with .Values.integration.wso2apim.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.integration.wso2apim.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.integration.wso2apim.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{ end }}
