{{ if .Values.integration.dependencies.postgresql }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.integration.postgresql.name }}-secrets
type: Opaque
data:
  POSTGRES_DB: cG9zdGdyZXM=
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
{{ end }}