{{ if .Values.integration.dependencies.wso2mi }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.integration.wso2mi.serviceName }}
  namespace : {{ .Release.Namespace }}
  labels:
    {{- include "wso2mi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.integration.wso2mi.service.type }}
  ports:
    # ports that this service should serve on
    - name: pass-through-https
      protocol: TCP
      port: 8253
      targetPort: 8253
    - name: pass-through-http
      protocol: TCP
      port: 8290
      targetPort: 8290
    - name: metrics-http
      protocol: TCP
      port: 9201
      targetPort: 9201
  selector:
    {{- include "wso2mi.selectorLabels" . | nindent 6 }}
{{ end }}